name: Test on Pull Request

on:
  pull_request:

permissions:
  contents: read
  checks: write

concurrency:
  group: sdk-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    name: 🧪 Run tests and report
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: ⚙️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.4.2

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 📦 Install deps
        run: bun install --frozen-lockfile

      - name: 🎨 Check formatting
        run: bun run format:check

      - name: 🔎 Lint
        run: bun run lint

      - name: 🧩 Check types
        run: bun run check

      - name: 🛠️ Build
        run: bun run build

      - name: 🧪 Test
        run: bun run test -- --reporter=junit --outputFile=report.xml
        continue-on-error: false

      - name: 📊 Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          comment-on: none

      - name: 📈 Test Report
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: Vitest
          path: report.xml
          reporter: jest-junit
